import fs from "fs";
import path from "path";

type Product = { id: string; title: string; category: string; image: string };

const CATS = [
  { slug: "phones",  tag: "smartphone" },
  { slug: "bags",    tag: "handbag" },
  { slug: "clothes", tag: "clothes" },
  { slug: "books",   tag: "book" },
  { slug: "mug",     tag: "mug" },
  { slug: "laptops", tag: "laptop" },
  { slug: "shoes",   tag: "shoes" },
  { slug: "tshirt",  tag: "tshirt" },
  { slug: "shirts",  tag: "shirt" },
  { slug: "scenery", tag: "scenery" }, // (your “scenary”)
  { slug: "jackets", tag: "jacket" },
  { slug: "watches", tag: "watch" }
];

const PER_CAT = 900; // 12 x 900 = 10,800 items
const SIZE = "640/640";

const items: Product[] = [];
for (const cat of CATS) {
  for (let i = 1; i <= PER_CAT; i++) {
    const id = `${cat.slug}-${i}`;
    const title = `${cat.slug[0].toUpperCase()}${cat.slug.slice(1)} ${i}`;
    const image = `https://loremflickr.com/${SIZE}/${encodeURIComponent(cat.tag)}?lock=${i}`;
    items.push({ id, title, category: cat.slug, image });
  }
}

const out = `// AUTO-GENERATED by scripts/gen-products.ts
export type Product = { id: string; title: string; category: string; image: string }
export const PRODUCTS: Product[] = ${JSON.stringify(items, null, 2)}
`;

fs.mkdirSync(path.join("src", "data"), { recursive: true });
fs.writeFileSync(path.join("src", "data", "products.ts"), out);
console.log("Wrote", items.length, "items to src/data/products.ts");